name: DootDoot Actions
run-name: ${{ github.actor }} is running DootDoot GitHub Actions 🚀
on:
  push:
    branches:
      - 'main'
jobs:
  Code-Coverage-Report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn install
      - run: yarn coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
